CREATE TABLE IF NOT EXISTS "book" (
    book_id SERIAL NOT NULL PRIMARY KEY,
    book_title VARCHAR(255) NOT NULL,
    author_id INT NOT NULL REFERENCES "author" ("author_id"),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);