CREATE TABLE IF NOT EXISTS "author" (
    author_id SERIAL NOT NULL PRIMARY KEY,
    author_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);